# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest

CMD ["/bin/bash", "-c", "sleep infinity"]
# aglamn next line uncommented as of PPT slide 36 of the *outdated* IBM training documentation
CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
